# NumPy Arrays

before proceeding towards pandas data structure ,let us have a brief review of numPy arrays because -

NumPY ("Numerical python" or Numeric python")is an open source model of python the provides function for fast mathematical compulation on arrays and matrices.

NumPy arrays come in two forms

1-D array-also known as vector.
multimentional arrays- also known as Matrices

In [60]:
import numpy as np
lst=[1,2,3,4]
a1=np.array(lst)
lst


[1, 2, 3, 4]

In [61]:
print(a1)

[1 2 3 4]


In [62]:
a1

array([1, 2, 3, 4])

## NumPy Arrays vs Pyhthon lists

Although NumPy array also holds elements like python list ,yet numpy arrays are different data structure from python list. The key difference are-

once NumPy array is created ,you cannot change its size. you will have to create a new array or overwrite the exixting one.

NumPY array contain element of homogenous type,unlike python list

An equivalent NumPy array occupies much less space than a python list.

NumPy array supports Vectorized operation,i.e,you need to perform any functio n on every item one by one which is not in

In [63]:
import numpy as np
lst=[1,2,3,4]
a1=np.array(lst)
lst


[1, 2, 3, 4]

In [64]:
a1+2

array([3, 4, 5, 6])

# NumPy Data Types

### NumPy supports following data types-

# Ways to create NumPy Arrays

1.array () fumction can be used to create array-

numpy.array(<arrayconvertible object>,[<datatype>])

* Assuming NumPy has been imported as np.

In [65]:
import numpy as np
narl=np.array([2,5.2,1,0])
narl

array([2. , 5.2, 1. , 0. ])

above statement will do the following things-

### creating array be specifying own datatype

In [66]:
l=[1,2,3,4]
ar=np.array(l,dtype=np.int64)
ar

array([1, 2, 3, 4], dtype=int64)

In [67]:
l=[1,2,3,4]
ar=np.array(l,dtype=np.int32)
ar

array([1, 2, 3, 4])

In [68]:
print(type(ar))

<class 'numpy.ndarray'>


In [69]:
print(ar.dtype)

int32


In [70]:
print(ar.itemsize)

4


### 2.Create ndarray using fromiter()-

the fromiter() function is useful when you want to create an ndarray from a non-numeric sequence.

numpy.fromiter(<iterable sequence name>,<target data type>,[<count>])

In [71]:
ad={1:"A",2:"B",3:"C",4:"D",5:"E"}
ar2=np.fromiter(ad,dtype=np.int32)
print(ar2)

[1 2 3 4 5]


In [72]:
ar2.dtype

dtype('int32')

In [73]:
ar2.itemsize

4

In [74]:
print(ar2[0],ar2[3])

1 4


In [75]:
ar2[3]

4

## 3.arange () function is used to create array from a range

<arrayname>=numpy.arange([start],stop,[sleep],[dtype])

In [76]:
import numpy as np
arr1=np.arange(5)
arr1

array([0, 1, 2, 3, 4])

## 4.linespace() function can be used to prepare array of range

<arangename>=numpy.linespace([start],stop,[dtype])

In [77]:
import numpy as np
arr3=np.linspace(2,3,6)
arr3

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [78]:
import numpy as np
arr4=np.linspace(2.5,5,8)
arr4

array([2.5       , 2.85714286, 3.21428571, 3.57142857, 3.92857143,
       4.28571429, 4.64285714, 5.        ])

## 2D NumPy Arrays

In [79]:
import numpy as np
A=np.array([[10,11,12,13],[21,22,23,24]])
A[1,3]

24

In [80]:
A[1][3]

24

In [81]:
A

array([[10, 11, 12, 13],
       [21, 22, 23, 24]])

In [82]:
print(A)

[[10 11 12 13]
 [21 22 23 24]]


In [83]:
type(A),type(a1)

(numpy.ndarray, numpy.ndarray)

In [84]:
A.shape

(2, 4)

In [85]:
A.itemsize

4

## 2.creating 2D ndarrays using arange()-

in the similer manner as we have created 1D ndarrays with arange() function,we can also create 2D ndarrays with arange()function along with reshape().

<ndarray>.reshape(<shape tuple>)

In [86]:
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ar3=ar1.reshape(5,2)
ar3

## 3.Arrays Creation Alternative methods

a.using empty()-

empty()function can be used to create empty array or an unintialized array of specified shape and dtype.

numpy.empty(shape,[dtype=<datatype>,][order='c' or 'f']

where:dtype:is a data type of python or numpy to set initial values.

shape:is dimension

order:'C' means arrangment of data as row wise(C means C like).

order:'F' means arrangment of data as row wise(F means fortan like)

In [87]:
arr1=np.empty([2,3],dtype=np.int64,order='c')
arr1

array([[4611686018427387904, 4612136378390124954, 4612586738352862003],
       [4613037098315599053, 4613487458278336102, 4613937818241073152]],
      dtype=int64)

In [88]:
arr1=np.ones([2,3],dtype=np.int64,order='c')
arr1

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

# b.using zeros()-

In [89]:
arr1=np.zeros([2,3],dtype=np.int64,order='c')
arr1

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

## Array Slicing-

it is possible to extract subsets of numpy arrays using slices,just like lists.

<arrayname>[<start>:<stop>:<step>]

*when<start><stop><state>values are not specified then python will assume their default value as:
start=0;stop=dimension size;step=1

In [90]:
arr=np.array([2,4,6,8,10,12,14,16])
arr[3:7]

array([ 8, 10, 12, 14])

In [91]:
arr[:5]

array([ 2,  4,  6,  8, 10])

In [92]:
arr[4:]

array([10, 12, 14, 16])

In [93]:
arr[:-1]

array([ 2,  4,  6,  8, 10, 12, 14])

In [94]:
arr[-1:]

array([16])

In [95]:
arr[2:7:2]

array([ 6, 10, 14])

In [96]:
arr[:-3]

array([ 2,  4,  6,  8, 10])

# joing or concatenation NumPy arrays-

for joing or concatating of two or more exixting ndarrays,python provides following functions-


    

 1.hask()and vstack()

   2.concated()

In [97]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
a1=np.array(list1)
a1

array([1, 2, 3, 4, 5])

In [98]:
a2=np.array(list2)
a2

array([ 6,  7,  8,  9, 10])

In [99]:
join1=np.hstack((a1,a2))
join1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
join2=np.vstack((a1,a2))
join2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# combinnig existing arrays using concatenate()-

In [101]:
a1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
a2=np.array([1,2,3,4,5,6]).reshape(2,3)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a3=np.array([1,2,3,4,5,6]).reshape(3,2)
a3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
a4=np.array([1,2,3]).reshape(3,1)
a4

array([[1],
       [2],
       [3]])

In [105]:
j1=np.concatenate((a1,a2),axis=0)
j1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [106]:
j2=np.concatenate((a1,a3),axis=1)
j2

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4],
       [7, 8, 9, 5, 6]])

In [107]:
j3=np.concatenate((a1,a4),axis=1)
j3

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

## Obtaining subsets of arrays

In [108]:
ary=np.arange(24.0).reshape(4,6)
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [109]:
np.hsplit(ary,2)

[array([[ 0.,  1.,  2.],
        [ 6.,  7.,  8.],
        [12., 13., 14.],
        [18., 19., 20.]]),
 array([[ 3.,  4.,  5.],
        [ 9., 10., 11.],
        [15., 16., 17.],
        [21., 22., 23.]])]

In [110]:
np.vsplit(ary,2)

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])]

## b.using the split() function-

In [111]:
ar1d=[10,11,12,13,15,15,16,17,18,19]
np.split(ar1d,[2,6])

[array([10, 11]), array([12, 13, 15, 15]), array([16, 17, 18, 19])]

In [112]:
ary=np.arange(24.0).reshape(4,6)
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [113]:
np.split(ary,[1,4])

[array([[0., 1., 2., 3., 4., 5.]]),
 array([[ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

In [114]:
np.split(ary,[2,5],axis=1)

[array([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.]]),
 array([[ 2.,  3.,  4.],
        [ 8.,  9., 10.],
        [14., 15., 16.],
        [20., 21., 22.]]),
 array([[ 5.],
        [11.],
        [17.],
        [23.]])]

In [115]:
np.split(ary,[2,4])

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

In [116]:
np.split(ary,[2,5],axis=0)

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

## Extracting condition based non-contiguous subsets

In [117]:
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [118]:
cond=np.mod(ary,5)==0
cond

array([[ True, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False]])

## Arithmetic operations on 2D arrays

## a.using operators-

In [119]:
ary+1.5

array([[ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5, 10.5, 11.5, 12.5],
       [13.5, 14.5, 15.5, 16.5, 17.5, 18.5],
       [19.5, 20.5, 21.5, 22.5, 23.5, 24.5]])

In [121]:
new=ary+2.1
ary+new

array([[ 2.1,  4.1,  6.1,  8.1, 10.1, 12.1],
       [14.1, 16.1, 18.1, 20.1, 22.1, 24.1],
       [26.1, 28.1, 30.1, 32.1, 34.1, 36.1],
       [38.1, 40.1, 42.1, 44.1, 46.1, 48.1]])

In [122]:
np.multiply(ary,3)

array([[ 0.,  3.,  6.,  9., 12., 15.],
       [18., 21., 24., 27., 30., 33.],
       [36., 39., 42., 45., 48., 51.],
       [54., 57., 60., 63., 66., 69.]])

# Application on numpy Arrays

## covariance

the intutive idea behind convariance is that it tells how similer variying two datasets are.A heigh positive covariance between 2 datsets means they are very strongly similar.similarly,a high negative convariance between 2 datasets means they are very dissimalar.

numpy.co(<arr1>m<arr2>)

In [124]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,0,-1,-3])
check=np.cov(a,b)
check

array([[ 2.5 , -4.25],
       [-4.25,  8.3 ]])

## 2.correlation

correlation is basically normalized covariance.it gives two values:1 if the data sets have positive convariance-1 if the datasets have negative convariance.

np.corrocoef(<array1>,array2>)

In [127]:
corr=np.corrcoef(a,b)
corr

array([[ 1.        , -0.93299621],
       [-0.93299621,  1.        ]])

# Thank You